### ISSUE TITLE
Conflict with Javadoc

### ISSUE THREAD

**Issue by glcj** [javierllorente/netbeans-rest-client#10] opened 2023-09-24 17:35 UTC
Hello,

With the NetBeans 19 version, it does not allow opening links to JavaDocs. Opening directly in the Rest client.

I did not find an immediate solution, just disable the module.

Thanks,

**Comment by javierllorente** [comment] 2023-09-27 22:34
Duplicate of #9

**Closed by javierllorente** 2023-09-27 22:34 UTC
